### PR TITLE
Seems like it should be like this

### PR DESCRIPTION
**Pull request by zim32**
isLower ==> isLess

### CODE REVIEW

**Comment by matthieuriolo** [comment]
Good point, but instead removing the old functions I will add the new one to it. Compatibility and stuff, deal?

**Comment by zim32** [comment]
If someone expects from "lt" to act like this it is sensible.. but do they.. That's the question )

**Comment by zim32** [comment]
Right now it just returns target value (as I understand)

**Comment by matthieuriolo** [comment]
Frankly, I think its not even correct from a grammar point of view... 5 is not lower then 6...

PS: The way you changed it, you broke the code. Dont worry, I will fix it for you

**Comment by matthieuriolo** [comment]
Sorry, it wasnt broken. I confused myself! I expected the original function still to be called isLower but it was already changed, not the shortcut declaration though.

Thx for your contribution!

**Comment by zim32** [comment]
Thanks

**Pull request merged**
